const projetosDados = [
    {
        id: 0,
        nome: 'Vade Mecum',
        link: 'https://github.com/RenanSantos7/Vade-Mecum',
        img: 'assets/projetos/vade-mecum.png',
        alt: 'Vade Mecum Tela Principal',
        descricao: '<p>Um projeto de <em>Vade Mecum</em>, o famoso compêndio de leis usados por estudantes e profissionais de Direito.</p>',
        texto: '<p>Um projeto de <em>Vade Mecum</em>, o famoso compêndio de leis usados por estudantes e profissionais de Direito.</p><p>Tem navegação simples e utiliza conceitos de HTML5, CSS3 e JavaScript para criar uma experiência de usuário única, preocupada com a legibilidade e acessibilidade.</p><figure><img src="assets/projetos/cf.png" alt="Vade Mecum Tela Lei"><figcaption>Constituição Federal</figcaption></figure><figure><img src="assets/projetos/cc.png" alt="Código Civil Vade Mecum"><figcaption>Código Civil</figcaption></figure><p>Ainda há modo escuro automático, que se adapta à escolha do usuário para seu sistema</p><figure><img alt="CPC no modo escuro com menu lateral" src="https://github.com/RenanSantos7/Vade-Mecum/blob/main/prints/cpc.png?raw=true"><figcaption>CPC no modo escuro com menu lateral</figcaption></figure><h2>Interface mobile</h2><figure><img src="https://github.com/RenanSantos7/Vade-Mecum/blob/main/prints/home-mobile.png?raw=true" alt="Tela principal no celular" class="vertical"><figcaption>Tela principal no celular</figcaption></figure><h2>Funcionalidades</h2><ul><li>Layout atual e responsivo;</li><li>Modo escuro;</li><li>Melhor legibilidade;</li><li>Adaptado para telas ultrawide</li><li>Facilidade de uso.</li></ul>',
        tecnologias: ['html', 'css', 'javascript'],
        atualizacao: '2023-12-14',
    },
    
    {
        id: 1,
        nome: 'Cardápio Pizzaria',
        link: 'https://github.com/RenanSantos7/Cardapio-QRCODE',
        img: 'assets/projetos/Captura-Cardapio.jpeg',
        alt: 'Vade Mecum Tela Principal',
        descricao: '<p>Um cardápio de pizzaria para ser usado com QRCode.</p>',
        texto: '<p>Um cardápio de pizzaria para ser usado com QRCode.</p><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates, fuga. Assumenda accusamus et secum iure quidem, aliquid facilis corporis nostrum a deserunt ipsa, aliquam ea iusto natus nisi.</p>',
        tecnologias: ['html', 'css', 'javascript'],
        atualizacao: '2023-03-25',
    },

    {
        id: 2,
        nome: 'Calculadora',
        link: 'https://github.com/RenanSantos7/Calculadora-JS',
        img: 'assets/projetos/calculadora.png',
        alt: 'Calculadora Tela Principal',
        descricao: '<p>Uma calculadora simples usando conceitos moderos de CSS3 e JavaScript.</p>',
        texto: '<p>Uma calculadora simples usando conceitos modernos de CSS3 e JavaScript.</p><p>Os números estão dispostos em <code>CSS grid</code>, o que torna todo o código HTML mais simples e fácil de programar no JavaScript.</p><p>Executa operações de soma, multiplicação, divisão e subtração.</p>',
        tecnologias: ['html', 'css', 'javascript'],
        atualizacao: '2023-09-13',
    },

    {
        id: 3,
        nome: 'Gerador de Tabelas',
        link: 'https://github.com/RenanSantos7/Gerador-de-tabelas',
        img: 'assets/projetos/gerador-tabela1.png',
        alt: 'Gerador de tabelas',
        descricao: '<p>Uma maneira fácil e rápida de gerar tabelas em <code>html</code></p>',
        texto: '<p>Sabe quando você precisa criar uma tabela em HTML? Não dá um trabalhão digitar TRs e TDs? Esse projeto te ajuda a simplificar esse processo. Basta definir o número de linhas e colunas e a tabela é gerada.</p><h2>Como Usar</h2><p>É muito simples usar o Gerador de Tabelas. Primeiro, defina o número de linhas e colunas e clique no botão "Gerar!"</p><p>Depois, uma tabela é gerada na página. Basta clicar em cada célular para editar seu conteúdo.</p><figure><img alt="Tela 1" src="assets/projetos/gerador-tabela2.png"></figure><p>Nessa tela você deve ainda selecionar se a tabela é no sentido vertical (com os títulos da tabela na primeira linha) ou horizontal (com os títulos na primeira coluna). O padrão é o sentido vertical.</p><p>Por fim, quando você clicar no botão "Gerar código", o código é exibido para você. Você pode selecionar o texto e copiá-lo ou clicar em &quot;Copiar&quot;.</p><figure><img alt="Tela 2" src="assets/projetos/gerador-tabela3.png"></figure><h2>Github Pages</h2><p>O projeto está disponível através do <a href="https://renansantos7.github.io/Gerador-de-tabelas/">Github Pages</a>.</p>',
        tecnologias: ['html', 'css', 'javascript'],
        atualizacao: '2023-10-02',
    },

    {
        id: 4,
        nome: 'Número Secreto',
        link: 'https://github.com/RenanSantos7/numero-secreto',
        img: 'https://github.com/RenanSantos7/numero-secreto/raw/main/screenshots/tela-jogo.jpg',
        alt: 'Número Secreto. Chute reconhecido',
        descricao: '<p>Um jogo bem divertido desenvolvido no curso <i>"JavaScript: validações e reconhecimento de voz"</i> da <b>Alura</b></p>',
        texto: '<p>Um projeto feito para o curso &quot;<strong>JavaScript: validações e reconhecimento de voz</strong>&quot; da Alura> com o professor Guilherme Lima.</p><p>Trata-se de um jogo bastante divertido em que se usa a Web Speech API para reconhecimento de voz. Você fala um número até acertar o número secreto que ele sorteou!</p><p>Aproveite e divirta-se!</p><p>O projeto está disponível pelo <a href="https://numero-secreto-git-main-renansantos7.vercel.app/">Vercel</a>.</p>',
        tecnologias: ['html', 'css', 'javascript', 'webspeech'],
        atualizacao: '2023-10-09',
    },
    
  /*   {
        id: 5,
        nome: 'Alura Play',
        link: 'https://github.com/RenanSantos7/curso-requisi-es-javascript-alura',
        img: 'https://camo.githubusercontent.com/265a1c9f8574dcf63c1a9de7c86d5d414a9ceec5c424c43ba21aa556c2a38c03/68747470733a2f2f696d6775722e636f6d2f61796d784573682e706e67',
        alt: 'Interface principal do alurapplay',
        descricao: '<p>Um projeto criado para o curso <i>"JavaScript: criando requisições"</i> da <b>Alura</b>.</p>',
        texto: '<p>Projeto criado para o curso &quot;<b>JavaScript: criando requisições</b>&quot; da Alura.</p><p>Contém página inicial e formulário de cadastro de vídeos da AluraPlay, uma plataforma de compartilhamento de vídeos.</p><p>Tecnologias utilizadas durante o curso:</p><ul><li>Javascript</li><li>NodeJS</li><li>Json-server</li></ul><p>Tecnologias utilizadas no projeto</p><ul><li>HTML</li><li>CSS</li></ul><p>Tecnologia que eu acrescentei ao projeot</p><ul><li>ESLint</li></ul>',
        tecnologias: ['html', 'css', 'javascript'],
        atualizacao: '2023-10-20',
    }, */

    {
        id: 6,
        nome: 'Alura SPA',
        link: 'https://github.com/RenanSantos7/alura-spa',
        img: 'https://github.com/RenanSantos7/alura-spa/blob/main/screenshots/Screenshot%201.png?raw=true',
        descricao: '<p>Um projeto criado para o curso "SASS: CSS sintaticamente espetacular" da <b>Alura</b>.</p>',
        alt: 'Tela Principal',
        texto: '<p>Um projeto criado para o curso <i>SASS: CSS sintaticamente espetacular</i> da Alura.</p><p>SASSS é um pré-processador de CSS, o que significa que ele ajuda você a desenvolver os estilos de uma página web e gera o código CSS que irá de fato ser lido pelo navegador.</p><p>Sua utilidade é meio polêmica e eu me filio a corrente de que ele não é necessário se você já conhece bastante de CSS. De qualquer forma, muitas vezes a escolha pelo uso dessa tecnologia não será sua e sim da equipe, então é sempre bom conhecê-la.</p><figure><img src="https://github.com/RenanSantos7/alura-spa/blob/main/screenshots/Screenshot%202.png?raw=true" alt="página web Alura Spa"></figure>',
        tecnologias: ['html', 'sass'],
        atualizacao: '2023-10-25',
    },

    {
        id: 7,
        nome: 'Organo APP',
        link: 'https://github.com/RenanSantos7/organo-app',
        img: './assets/projetos/organo-app.jpg',
        alt: 'Tela do Organao App',
        descricao: '<p>Um aplicativo desenvolvido em React para o curso "React: desenvolvendo com JavaScript" da <b>Alura</b>.</p>',
        texto: '<p>Esse é meu primeiro projeto usando React.js, o mais famoso framework de Javascript da atualidade. Foi muito interessante desenvolvê-lo pela curiosidade de aprender uma nova tecnologia. Além disso a didático do Professor Vinicios Neves foi muito boa, dando dicas muito legais de desenvolvimento e de uso do VSCode, sem contar sua participação ativa no Fórum do curso, sempre respondendo perguntas e dando <em>feedback</em> sobre a nossa evolução.</p><figure><img src="./assets/projetos/organo-app2.jpg" alt="Colabores cadastrados no Organo App"><figcaption>Colabores cadastrados no Organo App</figcaption></figure><p>Trata-se de um app React com o objetivo de cadastrar os colaboradores da Alura. Alguns já está cadastrados por padrão, mas você pode colocar mais se quiser.</p><p>O projeto está disponível em <a href="https://react-organo-app.vercel.app/">https://react-organo-app.vercel.app/</a> (Deploy pelo Vercel)</p>',
        tecnologias: ['react'],
        atualizacao: '2023-11-22',
    },

    {
        id: 8,
        nome: 'Rbank',
        link: 'https://github.com/RenanSantos7/rbank',
        img: './assets/projetos/rbank.jpg',
        alt: 'Tela Rbank',
        descricao: '<p>Projeto de site para um banco virtual fictício. Criado com base no projeto "Monibank" para o curso JavaScript: Validando Formulários da <b>alura</b>.</p>',
        texto: '<p>Este é Projeto de site para um banco virtual fictício. Criado com base no projeto "Monibank" para o curso JavaScript: Validando Formulários da alura.</p><p>Nele, trabalhei com validação de formulários de texto de diversos tipos, como CPF, RG, além de data e caixa de checagem.</p><p>Além do que o curso propõe, apliquei uma lógica de componentização com JavaScript puro e o tema escuro ao site.</p><h2>Tecnologias utilizadas durante o curso:</h2><ul><li>JavaScript</li></ul><h2>Tecnologias utilizadas no projeto:</h2><ul><li>HTML</li><li>CSS</li></ul><h2>Deploy</h2><ul><li>Vercel ➡️ https://rbank.vercel.app/</li></ul>',
        tecnologias: ['html', 'css', 'javascript'],
        atualizacao: '2023-12-19',
    },
    {
        id: 9,
        nome: 'Piw',
        link: 'https://github.com/RenanSantos7/piw',
        img: './assets/projetos/piw.jpg',
        alt: 'Tela Piw',
        descricao: '<p>Este é um projeto pessoal de uma rede social fake. A estrutura da página é inspirada no Twitter, no Bluesky e no Facebook.</p>',
        texto: '<p>Este é um projeto pessoal. Ele me veio à cabeça um manhã e não consegui resistir: fui logo codar. Trata-se de uma rede social fake. A estrutura da página é inspirada no Twitter, no <a href="https://staging.bsky.app">Bluesky</a> e no Facebook.</p><p>A parte mais divertida sem dúvida foi escrever os posts. Além disso, a logo da rede social foi criada pelo Bing AI e precisou só de um pequeno tratamento no Photopea.</p><p>O projeto é feito em React e as principais bibliotecas usadas são o <b>React Router DOM</b> e <b>Font Awesome Icons</b></p>',
        atualizacao: '2023-12-23',
        tecnologias: ['react'],
    },
    {
        id: 10,
        nome: 'Olá, mundo',
        link: 'https://github.com/RenanSantos7/ola-mundo-react-router',
        img: 'https://github.com/RenanSantos7/ola-mundo-react-router/blob/main/public/print-banner.png?raw=true',
        alt: 'banner do blog Olá mundo',
        descricao: '<p>Este é um projeto em React desenvolvido no curso "React: desenvolvendo em React Router com JavaScript" da <b>Alura</b>.</p>',
        texto: '<p>Este é um projeto em React desenvolvido no curso React: desenvolvendo em React Router com JavaScript da Alura.</p><h2>Tecnologias utilizadas</h2><ul><li>React (Create React App)</li><li>React Router DOM</li><li>React Markdown (<a href="https://www.npmjs.com/package/react-markdown" target="blank">https://www.npmjs.com/package/react-markdown</a>)</li></ul><h2>Como acessar online</h2><p>O deploy do projeto foi feito pelo Netilify e está disponível em <a href="https://ola-mundo-alura.netlify.app/" target="blank">https://ola-mundo-alura.netlify.app/</a></p><h2>Como rodar localmente</h2><p>Este projeto foi criado usando Create React App, portanto você pode seguir a documentação desse script para fazer deploy do site localmente.</p><p>No caso, primeiro você precisará baixar o projeto com o seguinte comando:</p><pre class="code-block"><code>git clone https://github.com/RenanSantos7/ola-mundo-react-router.git </code></pre><p>Agora, navegue até a raiz do projeto e abra um terminal. Nele rode o seguinte comando:</p><pre class="code-block"><code>npm start</code></pre><p>O navegador será aberto no endereço <code class="inline-code">http://localhost:3000</code> para que você possa visualizá-lo.</p>',
        tecnologias: ['react'],
        atualizacao: '2023-12-26',
    }
]

export default projetosDados
